# Generated by Django 2.2.16 on 2020-12-27 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20201113_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 14, 8, 56, 156179, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
